[package]
name = "fido-libfido2"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
build = "build.rs"

[features]
default = []
native-libfido2 = []

[lints]
workspace = true

[dependencies]
sha2 = "=0.10.9"
fido-auth = { path = "../fido-auth" }
