[package]
name = "fido-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
native-libfido2 = ["fido-libfido2/native-libfido2"]

[dependencies]
fido-core = { path = "../fido-core" }
fido-libfido2 = { path = "../fido-libfido2" }
fido-worker-protocol = { path = "../fido-worker-protocol" }
thiserror.workspace = true

[[example]]
name = "discover"
required-features = ["native-libfido2"]

[lints]
workspace = true
